apiVersion: v1
kind: Service
metadata:
  name: tindev-backend-svc
  labels:
    app: tindev-backend
    version: v1
spec:
  selector:
    app: tindev-backend
  type: LoadBalancer
  ports:
  - port: 3333
    protocol: TCP
    targetPort: 3333
