apiVersion: apps/v1
kind: Deployment
metadata:
  name: tindev-frontend
  labels:
    app: tindev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tindev-frontend
  template:
    metadata:
      labels:
        app: tindev-frontend
    spec:
      containers:
        - name: tindev-frontend
          image: diegomais/tindev-frontend
          env:
            - name: PORT
              value: '3000'
            - name: NEXT_PUBLIC_API_URL
              value: http://localhost:60403
          ports:
            - containerPort: 3000
