apiVersion: v1
kind: Service
metadata:
  name: tindev-frontend-svc
  labels:
    app: tindev-frontend
    version: v1
spec:
  selector:
    app: tindev-frontend
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
