name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "frontend"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: npx eslint --format=stylish src
      - name: Format
        run: npx prettier --check src
      - name: Build
        run: pnpm build
